services:
  db:
    image: postgres:15
    container_name: board-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: board
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data